package main

import (
	"github.com/lyft/protoc-gen-star"
)

func main() {
	pgs.Init(
		pgs.DebugMode(),
	).RegisterModule(
		NewBazelBuildGenerator(),
	).RegisterPostProcessor(
		NewPostProcessor(
			"Bazel build file is generated by protoc-gen-bazel. DO NOT EDIT.",
		),
	).Render()
}
